name: Fx Package Build

on:
  push:
    branches:
      - main

jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/

      - name: Configure .npmrc for third-party package
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.THIRD_PARTY_TOKEN }}" > ~/.npmrc
          echo "registry=https://npm.pkg.github.com/instantsys-labs" >> ~/.npmrc

      - run: npm install --force

      - run: ng build fx-builder-wrapper

      - run: cd dist/fx-builder-wrapper && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
